- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - curl
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev
    - bison

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    executable: /bin/zsh

- name: Install pyenv
  shell: >
    curl -o- https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv"
    executable: /bin/zsh

- name: Enable integration with shell
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'eval "$(pyenv init -)"'

- name: Enable virtualenv integration with shell
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'eval "$(pyenv virtualenv-init -)"'

- name: Install gvm
  shell: >
    zsh < <(curl -s -S -L https://raw.githubusercontent.com/bipinshashi/gvm/fix/zsh/binscripts/gvm-installer)
  args:
    executable: /bin/zsh
    creates: "{{ ansible_env.HOME }}/.gvm"

- name: Install node
  shell: >
    source ~/.zprofile
    nvm install --lts
  args:
    executable: /bin/zsh

- name: Install go
  shell: |
    source ~/.zprofile
    gvm install go1.21.0 -B
    gvm use go1.21.0
    export GOROOT_BOOTSTRAP=$GOROOT
    gvm install go1.21.5
    gvm use go1.21.5 --default
  args:
    executable: /bin/zsh

- name: Install python
  shell: |
    source ~/.zprofile
    pyenv install 3.8-dev
  args:
    executable: /bin/zsh


