- name: Install zsh
  become: true
  package:
    name: zsh
    state: present

- name: Set zsh as default shell
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: "Install oh-my-zsh"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: "Syslink all zsh files"
  file:
    src: "{{role_path}}/files/{{ item.src }}.sh"
    path: "{{ ansible_env.HOME }}/.{{ item.src }}"
    state: link
  with_items:
    - src: "zshrc"
    - src: "zshenv"
    - src: "zprofile"

- name: "Syslink p10k config"
  file:
    src: "{{role_path}}/files/p10k.zsh"
    path: "{{ ansible_env.HOME}}/.p10k.zsh"
    state: link
    force: true

- name: "Copy fonts over"
  copy:
    src: "files/fonts/"
    dest: "{{ ansible_env.HOME}}/.local/share/fonts"

- name: "Install powerlevel10k"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git 
    depth: 1
    dest: "{{ ansible_env.HOME}}/.oh-my-zsh/custom/themes/powerlevel10k"
