- name: Install zsh
  become: true
  package:
    name: zsh
    state: present

- name: Set zsh as default shell
  become: True
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: "Install oh-my-zsh"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: "Syslink all files"
  file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: link
  with_items:
    - src: "{{role_path}}/files/zshrc.sh"
      path: "{{ ansible_env.HOME }}/.zshrc"
    - src: "{{role_path}}/files/zshenv.sh"
      path: "{{ ansible_env.HOME }}/.zshenv"