- name: Install zsh
  become: true
  package:
    name: zsh
    state: present

- name: Set zsh as default shell
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: "Install oh-my-zsh"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: "Syslink all zsh files"
  file:
    src: "{{role_path}}/files/{{ item.src }}.sh"
    path: "{{ ansible_env.HOME }}/.{{ item.src }}"
    state: link
  with_items:
    - src: "zshrc"
    - src: "zshenv"
    - src: "zprofile"