mode = "git-commit"

[git]

[git.config]
email = "semverbot@github.com"
name = "semverbot"

[git.tags]
prefix = "v"

[semver]
patch = ["fix", "perf", "docs", "refactor", "chore", "ci"]
minor = ["feat"]
major = ["BREAKING CHANGE"]

[modes]

[modes.git-commit]
delimiters = ":"

