# Use this template to make configuration dynamic.
[[dependencies]]
name = "car"
install = "~/dotfiles/nvim"
config = "~/dotfiles/nvim"
enable = false

[[package_managers]]
name = "cargo"

[shell]
name = "shell_"

[editor]
name = "nvim"
