- name: Install pyenv
  shell: >
    curl -o- https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv"
    executable: /bin/zsh

- name: Enable integration with shell
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'eval "$(pyenv init -)"'

- name: Enable virtualenv integration with shell
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'eval "$(pyenv virtualenv-init -)"'

- name: Install python
  shell: |
    source ~/.zprofile
    pyenv install 3.8-dev
  args:
    executable: /bin/zsh
    creates:  "{{ ansible_env.HOME }}/.pyenv/versions/3.8-dev"

