- name: Check for cargo bin
  stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin"
  register: cargo_bin
- name: Install Rust
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755
    force: yes
  when: cargo_bin.stat.exists == False
  tags: 
    - rust
- name: Install Rust
  shell: /tmp/rustup.sh -y
  when: cargo_bin.stat.exists == False
  tags: 
    - rust