- name: Install fzf
  become: true
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1
  register: fzf_install

- name: Run fzf install script
  shell:
    cmd: ~/.fzf/install
    creates: ~/.fzf/bin/fzf
  when: fzf_install.changed