- name: "Install neovim dependencies"
  become: true
  package:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
    
- name: "Clone neovim"
  git:
    repo: "https://github.com/neovim/neovim.git"
    version: stable
    dest: /tmp/neovim
    force: true
  
- name: "Set make type"
  make:
    chdir: /tmp/neovim
    target: CMAKE_BUILD_TYPE=RelWithDebInfo

- name: "Install neovim"
  become: true
  make:
    chdir: /tmp/neovim
    target: install

- name: "Link config"
  file:
    src: "{{ role_path }}/files/"
    path: ~/.config/nvim
    state: link