- name: "Install neovim dependencies"
  become: true
  package:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip

- name: "Clone neovim"
  git:
    repo: "https://github.com/neovim/neovim.git"
    version: nightly
    dest: /tmp/neovim

- name: "Set make type"
  make:
    chdir: /tmp/neovim
    params:
      CMAKE_BUILD_TYPE: Release

- name: "Set make type and install neovim"
  become: true
  make:
    chdir: /tmp/neovim
    target: install

- name: "Link config"
  file:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
