- name: "Install neovim dependencies"
  become: true
  package:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip

- name: "Clone neovim"
  git:
    repo: "https://github.com/neovim/neovim.git"
    version: nightly
    dest: /tmp/neovim

- name: "Check if Neovim was cloned"
  stat:
    path: /tmp/neovim
  register: neovim_cloned

- name: "Set make type"
  when: neovim_cloned.stat.exists
  make:
    chdir: /tmp/neovim
    target: CMAKE_BUILD_TYPE=RelWithDebInfo

- name: "Install neovim"
  when: neovim_cloned.stat.exists
  become: true
  make:
    chdir: /tmp/neovim
    target: install

- name: "Link config"
  file:
    src: "{{ role_path }}/files/"
    path: ~/.config/nvim
    state: link
