- name: "install deps"
  become: true
  apt:
    state: present
    name:
      - libncurses5-dev
      # odbc
      - unixodbc
      - unixodbc-dev
      # wxWidgets
      - libglu1-mesa-dev
      - libwxgtk3.0-gtk3-dev
      # docs
      - xsltproc
      - fop
      - libxml2-utils
- name: "install erlang plugin"
  shell: "asdf plugin add erlang"
- name: "add erlang version >= 24"
  shell: "asdf install erlang 26.2.5"
- name: "set global erlang version"
  shell: "asdf global erlang 26.2.5"
- name: "install elixir"
  shell: "asdf plugin add elixir"
- name: "add erlang version >= 1.4"
  shell: "asdf install elixir 1.16.2"
- name: "set global elixir version"
  shell: "asdf global elixir 1.16.2"
- name: "install hex"
  shell: "mix local.hex"
