- name: Install ripgrep via cargo
  shell:
    cmd: cargo install ripgrep
    creates: ~/.cargo/bin/rg

- name: Install shell completions for ripgrep
  shell:
    cmd: |
      mkdir -p ~/.oh-my-zsh/completions
      rg --generate complete-zsh > ~/.oh-my-zsh/completions/_rg
    creates: ~/.oh-my-zsh/completions/_rg
