- name: Install gvm
  shell: |
    zsh < <(curl -s -S -L https://raw.githubusercontent.com/urmzd/gvm/fix/zsh/binscripts/gvm-installer)
  args:
    executable: /bin/zsh
    creates: "{{ ansible_env.HOME }}/.gvm"

- name: Install go
  shell: |
    source ~/.zprofile
    gvm install go1.21.0 -B
    gvm use go1.21.0
    export GOROOT_BOOTSTRAP=$GOROOT
    gvm install go1.21.5
    gvm use go1.21.5 --default
  args:
    executable: /bin/zsh
