- name: Install fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ansible_env.HOME}}/.fzf"
    depth: 1

- name: Run fzf install script
  command: ./.fzf/install
  args:
    chdir: "{{ansible_env.HOME}}"
